#!/bin/bash

FILEPATH="/home/sci/ssane/data/ML_Gerris/"
FILENO="2000"
EXT=".vtk"
SLICE=0
OUTPUT="FTLE/output_64_2"

DIMX=512
DIMY=512
DIMZ=1001

SDIMX=64
SDIMY=64

INTERVALS=2
NUM_STEPS=500
STEP_SIZE="0.01"

./ExtractTrainingData $FILEPATH $FILENO $EXT $OUTPUT $DIMX $DIMY $DIMZ $STEPS $SDIMX $SDIMY $INTERVALS $NUM_STEPS $STEP_SIZE
