#!/bin/bash

FILEPATH="/home/sci/ssane/data/ML_Gerris/"
FILENO="2000"
EXT=".vtk"

DIMX=512
DIMY=512
DIMZ=1001

SDIMX=64
SDIMY=64

INTERVALS=800
NUM_STEPS=200
STEP_SIZE="0.01"

OUTPUT="FTLE/output_"$SDIMX"_"$INTERVALS

./ExtractTrainingData $FILEPATH $FILENO $EXT $OUTPUT $DIMX $DIMY $DIMZ $STEPS $SDIMX $SDIMY $INTERVALS $NUM_STEPS $STEP_SIZE
